---
title: "Tidy Census"
author: "jl"
date: "2026-02-17"
output: html_document
---

## Let's get started


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Housekeeping

If you haven't done so yet, request an API key from the Census Bureau:  https://api.census.gov/data/key_signup.html You'll get an email to activate. You may have to try activating a few times. Once you get the key, save it. You'll need it later.

Create a directory for your files. Then set your working directory. 

**setwd("*FILE PATH*")**


Or you can use the drop-down menu: **Session -> Set Working Directory -> Choose Directory**

Make sure packages are installed and loaded. If you installed them previously, you don't need to again. Think of install.packages like going to the hardware store to buy a tool. You don't go back every time you need that tool.  

**install.packages("*package_name*")**.  # note the quotes here


install.packages("tidyverse") #main package for analysis
install.packages("dplyr") #R's version of SQL
install.packages("ggplot2") #for graphics
install.packages("knitr") #for creating results files
install.packages("psych") #for stats functions
install.packages("tidycensus") #for grabbing census data


We then use Library to get that that tool out of your toolbox. 
**library(*package_name*)**. # but no quotes here

library(tidyverse) 
library(dplyr) 
library(ggplot2) 
library(knitr) 
library(psych)
library(tidycensus)



## Census data

Using the API key that was emailed to you, run this code. You only need to run it once. It's like installing a package. IF YOU DID THIS IN A PREVIOUS CLASS, YOU DON'T NEED TO DO IT AGAIN.

census_api_key("PASTE IT HERE", install=TRUE)

The main commands to pull data are get_decennial and get_acs. You also need to include the geography, the variables and the year. There has been an issue with 2020 Decennial, skipping for now.

Let's grab one variable (median age) using get_acs. We need to tell it the geography level that we want, the state and the year. 

For a full list of geographies, go here: <https://walkerke.github.io/tidycensus/articles/basic-usage.html#geography-in-tidycensus>

The data defaults to the 5-year ACS, but you can tell tidycensus to pull the 1- or 3- year data by adding , survey = "acs1"

Here's we're requesting ACS data at the county level for variable B01002_001 for California in 2023. We're sticking the data we grab into a data frame called ca. You can refer to CA as "CA" or "06."


  ca <- get_acs(geography = "county", 
                variables = "B01002_001",
                state = "CA", 
                year = 2023)
  view(ca)

** Household income **

  cahhi <- get_acs(geography = "county", 
                variables = "B19013_001",
                state = "06", 
                year = 2023)

  view(cahhi)



Now grab the household income variable for census tracts in Alameda County:

 altrthhi <- get_acs(geography = "tract", 
                variables = "B19013_001",
                county="Alameda",
                state = "CA", 
                year = 2023)
                
  view(altrthhi)


**Census variables**

How did I know which variable to choose? Every census variable has a table code. You can run the full list of variables for a given survey or census:


  v2023 <- load_variables(2023, "acs5", cache = TRUE)
  view(v2023)


**Multiple variables**

To grab multiple variables, create an object for all the variables you want. Let's grab the median age variables by total and sex. Here's the list and description:

B01002_001 Total
B01002_002 Male
B01002_003 Female

  agevars <- c("B01002_001", "B01002_002", "B01002_003")

Replace the variable name with the variable list - agevars -- note that it is not in quotes:

  altrtage <- get_acs(geography = "tract", 
                variables = agevars,
                county="Alameda",
                state = "CA", 
                year = 2023)
  
  view(altrtage)

Notice how all the data is stacked? We can use the pivot_wider command to make it look like we're used to seeing data. You'll see lots of other data released this way, so it's a good command to know.


  wide_altrtage <- altrtage %>%
    pivot_wider(names_from = variable, values_from = c(estimate, moe))

  view(wide_altrtage)

We can use the select statement to give our columns names that make sense -- unless you want to memorize the hundreds of census tables. We also can leave out the MOEs (Margin of Error).

  pretty_altrtage <- wide_altrtage %>% select(GEOID,NAME,medage=estimate_B01002_001, male_age = estimate_B01002_002, fem_age = estimate_B01002_003)

If you get an error above, try adding dplyr:: to the front of your select statement.


  view(pretty_altrtage)


## Race variables

Let's pull race data by for Alameda tracts. 

  racevars <- c("B03002_001", "B03002_002", "B03002_003", "B03002_004", "B03002_005", "B03002_006", "B03002_007", "B03002_008","B03002_009", "B03002_012")
  
  alameda <- get_acs(geography = "tract", 
                variables = racevars,
                state = "CA",
                county="Alameda",
                year = 2023)
  view(alameda)


**Fix the stacked up data**

  wide_alameda <- alameda %>%
    pivot_wider(names_from = variable, values_from = c(estimate, moe))
  view(wide_alameda)


**Select what we want**

  pretty_alameda <- wide_alameda %>% dplyr::select(GEOID,NAME,pop=estimate_B03002_001, not_hisp = estimate_B03002_002, white = estimate_B03002_003, black = estimate_B03002_004, am_ind = estimate_B03002_005, asian = estimate_B03002_006, pac_isl = estimate_B03002_007, other = estimate_B03002_008, mult = estimate_B03002_009, hispanic = estimate_B03002_012)
  
  view(pretty_alameda)


## Mutate

What if we also wanted to include percentages? We can use the mutate command to do calculations. 

  pretty_alameda %>% mutate(pct_white=white/pop)

Let's format it to make it look like a whole number:

  pretty_alameda %>% mutate(pct_white=100*(white/pop))

To round it to one decimal point:

  pretty_alameda %>% mutate(pct_white=round(100*(white/pop),1))

Put it all together and save it to a new data frame!


  alameda_fin <- pretty_alameda %>% mutate(pct_white=round(100*(white/pop),1)) %>% 
                 mutate(pct_black=round(100*(black/pop),1)) %>% 
                 mutate(pct_am_ind=round(100*(am_ind/pop),1)) %>% 
                 mutate(pct_asian=round(100*(asian/pop),1)) %>% 
                 mutate(pct_pac_isl=round(100*(pac_isl/pop),1)) %>% 
                 mutate(pct_other=round(100*(other/pop),1)) %>% 
                 mutate(pct_mult=round(100*(mult/pop),1)) %>% 
                 mutate(pct_hisp=round(100*(hispanic/pop),1))
  
  view(alameda_fin)


## Practice 2: Grab race data for CA counties

Steps:
1. Pull the data 
2. Make it wider
3. Select and rename columns
4. Compute percentages
5. Admire your new data frame


## Practice 3: Your choice of geography and census variables, but pick something with multiple categories. Remember that v2023 is the list of variables we created earlier.

Steps:
1. Identify the table you want and create a list.
2. Pull the data 
3. Make it wider
4. Select and rename columns
6. Compute percentages - if you're using raw numbers (not for medians)






